# SurvivalGames v1.0 by vduuude. This is a test config.
# Test

Lobby:
world: 'world'
spawn: ''
Game: 'false'
Tier1items:
- ==: org.bukkit.inventory.ItemStack
  type: STICK
- ==: org.bukkit.inventory.ItemStack
  type: BOW
- ==: org.bukkit.inventory.ItemStack
  type: LEATHER_HELMET
- ==: org.bukkit.inventory.ItemStack
  type: LEATHER_CHESTPLATE
- ==: org.bukkit.inventory.ItemStack
  type: LEATHER_LEGGINGS
- ==: org.bukkit.inventory.ItemStack
  type: LEATHER_BOOTS
- ==: org.bukkit.inventory.ItemStack
  type: ARROW
  amount: 5
- ==: org.bukkit.inventory.ItemStack
  type: STONE_SWORD
- ==: org.bukkit.inventory.ItemStack
  type: WOOD_SWORD
- ==: org.bukkit.inventory.ItemStack
  type: STONE_AXE
- ==: org.bukkit.inventory.ItemStack
  type: BAKED_POTATO
- ==: org.bukkit.inventory.ItemStack
  type: RAW_FISH
- ==: org.bukkit.inventory.ItemStack
  type: RAW_CHICKEN
- ==: org.bukkit.inventory.ItemStack
  type: RAW_BEEF
- ==: org.bukkit.inventory.ItemStack
  type: PUMPKIN_PIE
Tier2items:
- ==: org.bukkit.inventory.ItemStack
  type: STICK
- ==: org.bukkit.inventory.ItemStack
  type: BOW
- ==: org.bukkit.inventory.ItemStack
  type: DIAMOND
- ==: org.bukkit.inventory.ItemStack
  type: IRON_HELMET
- ==: org.bukkit.inventory.ItemStack
  type: IRON_CHESTPLATE
- ==: org.bukkit.inventory.ItemStack
  type: IRON_LEGGINGS
- ==: org.bukkit.inventory.ItemStack
  type: IRON_BOOTS
- ==: org.bukkit.inventory.ItemStack
  type: GOLD_HELMET
- ==: org.bukkit.inventory.ItemStack
  type: GOLD_CHESTPLATE
- ==: org.bukkit.inventory.ItemStack
  type: GOLD_LEGGINGS
- ==: org.bukkit.inventory.ItemStack
  type: GOLD_BOOTS
- ==: org.bukkit.inventory.ItemStack
  type: CHAINMAIL_HELMET
- ==: org.bukkit.inventory.ItemStack
  type: CHAINMAIL_CHESTPLATE
- ==: org.bukkit.inventory.ItemStack
  type: CHAINMAIL_LEGGINGS
- ==: org.bukkit.inventory.ItemStack
  type: CHAINMAIL_BOOTS
- ==: org.bukkit.inventory.ItemStack
  type: IRON_INGOT
- ==: org.bukkit.inventory.ItemStack
  type: FLINT_AND_STEEL
- ==: org.bukkit.inventory.ItemStack
  type: STONE_SWORD
- ==: org.bukkit.inventory.ItemStack
  type: ARROW
  amount: 5
- ==: org.bukkit.inventory.ItemStack
  type: GOLDEN_APPLE
- ==: org.bukkit.inventory.ItemStack
  type: GOLDEN_CARROT
- ==: org.bukkit.inventory.ItemStack
  type: COOKED_BEEF